# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Kayodé's Test Site
email: kayode@kayode.co
description: >-
  Articles, stories, and books by Kayodé Lycaon, furry author and software developer.
permalink: :year/:title
date_format: "%b %-d, %Y" # e.g. "Jan 1, 2020"

header_pages:
  - index.md
  - pages/books.md
  - pages/stories.md
  - about.md
  - pages/ref.md
collections:
  books:
    output: false
    sort_by: date
  stories:
    output: false
    sort_by: date

markdown: kramdown
plugins:
  - jekyll-feed
liquid:
  strict_filters: true

defaults:
  - scope:
      path: ""
    values:
      author: kayode_lycaon
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # - scope:
  #     path: ""
  #     type: "books"
  #   values:
  #     layout: "book"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - "**/_template.md"