# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Kayodé Lycaon
subtitle: "Painted Wolf, Furry Writer, and Software Developer"
email: kayode@kayode.co
description: >-
  Articles, stories, and books by Kayodé Lycaon, furry author and software developer.
permalink: blog/:year/:title
date_format: "%b %-d, %Y" # e.g. "Jan 1, 2020"
timezone: "America/New_York"

collections:
  books:
    output: false
    sort_by: date
  stories:
    output: false
    sort_by: date

markdown: kramdown
plugins:
  - jekyll-feed
  # - jekyll-paginate
liquid:
  strict_filters: true

defaults:
  - scope:
      path: ""
    values:
      author: kayodelycaon
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      nav_id: blog
  - scope:
      path: ""
      type: redirects
    values:
      layout: redirect
  # - scope:
  #     path: ""
  #     type: "books"
  #   values:
  #     layout: "book"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - "**/_template.md"
  - "*.pxd"
  - images/social-media/originals/
  - _notes/
